site1/blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    # ex: /
    url(r'^$', views.index, name='index'),
    # ex: /5/
    url(r'^(?P<blogpost_id>[0-9]+)/$', views.detail, name='detail'),
]

site1/site1/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
	url(r'^blog/', include('blog.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'' , include('blog.urls')),
]

site1/blog/models.py
import datetime

from django.db import models
from django.utils import timezone

class Blogpost(models.Model):
    
    title = models.CharField(max_length=255)
    
    body_text = models.TextField()
    
    pub_date =  models.DateTimeField('date published')
    
    def __str__(self):
		
        return self.title
        
    #for django admin - later
    def was_published_recently(self):
		
        now = timezone.now()
        
        return now - datetime.timedelta(days=2) <= self.pub_date <= now

class Comment(models.Model):
    
    blogpost = models.ForeignKey(Blogpost, on_delete=models.CASCADE)
    
    commentee = models.CharField(max_length=100, default='')
    
    comment_text = models.TextField()
    
    pub_date =  models.DateTimeField('date published')
    
    votes = models.IntegerField(default=0)
    
    def __str__(self):
		
        return self.comment_text
    
    #for django admin - later
    def was_published_recently(self):
		
        now = timezone.now()
        
        return now - datetime.timedelta(days=2) <= self.pub_date <= now

site1/blog/forms.py
from django.db import models
from django.forms import ModelForm, Textarea
from django.core.exceptions import NON_FIELD_ERRORS
from .models import Comment

class CommentForm(ModelForm):
	
	class Meta:
		
		model = Comment
		fields = ['commentee', 'comment_text']
		widgets = {
			'comment_text': Textarea(attrs={'cols': 40, 'rows': 4}),
		}

site1/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader, Context, RequestContext
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.views.decorators.http import require_http_methods

from .models import Blogpost, Comment
from .forms import CommentForm

@require_http_methods(["GET"])
def index(request):
	
	latest_blog_list = Blogpost.objects.order_by('-pub_date')[:6]
	
	
	return render(request, 'blog/index.html',
	{'latest_blog_list': latest_blog_list,}, RequestContext(request))
	
@require_http_methods(["GET", "POST" ])
def detail(request, blogpost_id): 
	
	blogpost = get_object_or_404(Blogpost, pk=blogpost_id)
	#quick solution, probably not the best
	ordered_comment_list = Comment.objects.filter(blogpost__id=blogpost_id).order_by('-pub_date')
	
	c = Context({
			
			'blogpost': blogpost,
			'form': CommentForm(),
			'ordered_comment_list': ordered_comment_list,
			
			})
	
	if request.method == 'POST':
		
		f = CommentForm(request.POST)
		
		try:
			
			new_comment = f.save(commit=False)
			
		except (ValueError):
			
			#return to commenting form with error message
			
			return render(request, 'blog/detail.html', c)
			
		else:
			
			#save the comment
			
			new_comment.pub_date = timezone.now()
			new_comment.blogpost = blogpost
			new_comment.votes = 0
			new_comment.save()

			return HttpResponseRedirect(reverse('blog:detail',args=(blogpost_id,)))
			
	else: #reques.method == 'GET'
		
											 # , ,specific context, global context
		return render(request, 'blog/detail.html', c,RequestContext(request))
	
	
	
	
	

site1/blog/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
	
  <head>
	  
	<title>{% block title %} Base {% endblock title %}</title>
	
	{% block head_meta %}
	
		{% block head_meta_charset %}
		
			<meta charset="utf-8">
			
		{% endblock head_meta_charset %}
		
		{% block head_meta_contentlanguage %}
		
            <meta http-equiv="Content-Language" value="en-US" />
            
        {% endblock head_meta_contentlanguage %}
        
		{% block head_meta_viewport %}
		
			<meta name="viewport" content="width=device-width, initial-scale=1.0">
			
		{% endblock head_meta_viewport %}
		
	{% endblock head_meta %}
	
	{% block head_css %}
	
		{% block head_css_site %}
		
			<!-- Latest compiled and minified CSS -->
			<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
			
			<!-- site main css -->
			<link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}" />
			
			<!-- jQuery library -->
			<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
			
			<!-- Latest compiled JavaScript -->
			<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
			
		{% endblock head_css_site %}
		
		{% block head_css_section %}{% endblock head_css_section %}
		
		{% block head_css_page %}{% endblock head_css_page %}
		
		{% block head_css_custom %}{% endblock head_css_custom %}
		
	{% endblock head_css %}
	
  </head>
  
  <body>
	  
	<header>
		
        <div class="navbar navbar-inverse navbar-static-top 
        {% block nav-style %}{% endblock %}">
        
            <div class="container">
				
                <div class="navbar-header">
					
                    <button type="button" class="navbar-toggle"
                            data-toggle="collapse"
                            data-target=".navbar-collapse">
                            
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        
                    </button>
                    
					<a class="navbar-brand" href="#">Blogger's blog</a>
                    
                </div>
                
                <ul class="nav navbar-nav">
					
					<li class="active"><a href="{% url 'blog:index' %}">Home</a></li>
					
				</ul>
            </div>
        </div>
    </header>
    
    <div class="container">
		
		<div class="row">
			
			<div class="col-sm-2" id="left-section">
				
				{% block left_column_content %}{% endblock left_column_content %}
				
			</div>
			
			<div class="col-sm-7" id="middle-section">
				
				{% block middle_content %}{% endblock middle_content %}
				
			</div>
			
			<div class="col-sm-2 col-sm-offset-1" >
				
				<div class="row" id="right-section">
					
					<div class="panel panel-default comment-panel" >
						
						<div class="panel-heading"><b>Recent posts</b></div>
						
						<div class="panel-body">
							
							{% for blogpost in recent_posts %}
							
								<a href="{% url 'blog:detail' blogpost.id %}"><li>{{ blogpost.title }}</a></li>
								
							{% empty %}
							
								<li>No recent posts</li>
								
							{% endfor %}
							
						</div>
						
						<br>
						
					</div>
					
					{% block right_column_content %}
						
					{% endblock right_column_content%}
					
				</div>
			</div>
		</div>
		
		<div class="row">
			
			<div class="footer">
				
			{% block footer_content%}{% endblock footer_content%}
			
			</div>
		</div>
	</div>
  </body>
</html>

site1/blog/templates/blog/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block head_css_custom %}
	<!-- index css -->
	<link rel="stylesheet" type="text/css" href="{% static 'blog/detail.css' %}" />
{% endblock head_css_custom %}

{% block title %}{{ blogpost.title }}{% endblock title %}


{% block left_column_content %}
{% endblock left_column_content %}
{% block middle_content %}   
	
	<div class="row blogpost">
		
		<div class = "col-sm-12">
			
			<h2>{{ blogpost.title }}</h2>
			
			<br>
				
			<!-- to enable html code in body_text -->
			{% autoescape off %}
			
				{{ blogpost.body_text }}
				
			{% endautoescape %}
			
		</div>
	
	</div>
	
	<div class="row blogpost2">
		
		<div class= "col-sm-8"></div>
				
		<div class= "col-sm-4">
			
			<br>
			
			<p class="text-muted">published {{ blogpost.pub_date }}</p>
			
		</div>
		
	</div>
			
		
	<div class="row blogpost">
		<button data-toggle="collapse" data-target="#comment-collapse">
			
			Comment
			
		</button>
		
		<br>
		
		<div id="comment-collapse" class="collapse">
			
		<form action="{% url 'blog:detail' blogpost.id %}" method="post">
			
			{% csrf_token %}
			
			{{ form.non_field_errors }}
			
			<div class="fieldWrapper">
				
				{{ form.commentee.errors }}
				
				<label for="{{ form.commentee.id_for_label }}"><br>Name</label><br>
				
				{{ form.commentee }}
				
			</div>
			
			<div class="fieldWrapper">
				
				{{ form.comment_text.errors }}
				
				<label for="{{ form.comment_text.id_for_label }}">Comment</label><br>
				
				{{ form.comment_text }}
				
			</div>
			
			<input type="submit" value="Submit" />
			
		</form>
		
		</div>
	</div>
	<div class="row blogpost2">
		<br>
		
		{% for comment in ordered_comment_list %}
				
		
			<div class="panel panel-default comment-panel " >
				
				<div class="panel-heading"><b>{{ comment.commentee }}  wrote:</b></div>
				
				<div class="panel-body">{{ comment.comment_text}}</div>
				
				<br />
				
				<div class="panel-footer fixed-panel"><p class="text-muted"><span style="float:right">{{ comment.pub_date}}</span></p></div> 
				
			</div>
			
			
		{% endfor %}
	</div>

{% endblock middle_content %}

site1/blog/templates/blog/index.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block head_css_custom %}

<!-- index css -->
<link rel="stylesheet" type="text/css" href="{% static 'blog/index.css' %}" />
	
{% endblock head_css_custom %}

{% block title %}Blogger's blog{% endblock title %}

{% block middle_content %}   

{% if latest_blog_list %}

{% for blogpost in latest_blog_list %}
    
<a href="{% url 'blog:detail' blogpost.id %}">
	
	<div class="row blogpost">
		
		<div class = "col-sm-12">
			
			<h2>{{ blogpost.title }}</h2>
			
			<br>
	
			<!-- to enable html code in body_text -->
			{% autoescape off %}
			
				{{ blogpost.body_text }}
				
			{% endautoescape %}
			
		</div>
	</div>

	<div class="row blogpost2">
		
		<br>
			
		<p class="text-muted ">published {{ blogpost.pub_date }}</p>
			
	</div>
	
</a> 

{% endfor %}

{% else %}

<p>No blogs have been posted</p>

{% endif %}

{% endblock middle_content %}

site1/blog/templates/blog/navbar.html
<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<div class="navbar-header">
			<a class="navbar-brand" href="#">Blogger's blog</a>
		</div>
		<ul class="nav navbar-nav">
			<li class="active"><a href="{% url 'blog:index' %}">Home</a></li>
		</ul>
	</div>
</nav>